export const truckingServiceItems = [
  {
    name: "IFTA Quarterly Filing",
    description: "International Fuel Tax Agreement quarterly tax return preparation and filing for interstate carriers.",
    category: "Tax & Compliance",
    defaultPrice: "450.00",
  },
  {
    name: "MCS-150 Biennial Update",
    description: "Mandatory biennial update of motor carrier information with FMCSA.",
    category: "DOT Compliance",
    defaultPrice: "150.00",
  },
  {
    name: "UCR Annual Registration",
    description: "Unified Carrier Registration annual renewal for interstate operations.",
    category: "Registration",
    defaultPrice: "175.00",
  },
  {
    name: "Annual DOT Compliance Review",
    description: "Comprehensive annual review of DOT compliance documentation, driver files, and vehicle records.",
    category: "DOT Compliance",
    defaultPrice: "1250.00",
  },
  {
    name: "Business Entity Setup",
    description: "LLC formation, EIN application, and initial business structure setup for new trucking companies.",
    category: "Business Setup",
    defaultPrice: "1800.00",
  },
  {
    name: "Quarterly Tax Preparation",
    description: "Quarterly estimated tax calculation and filing for trucking businesses.",
    category: "Tax & Compliance",
    defaultPrice: "350.00",
  },
  {
    name: "Bookkeeping - Monthly Service",
    description: "Monthly bookkeeping service including bank reconciliation, expense categorization, and financial reporting.",
    category: "Bookkeeping",
    defaultPrice: "50.00",
  },
  {
    name: "Permit & Authority Filing",
    description: "Filing for operating authority, permits, and interstate carrier credentials.",
    category: "Registration",
    defaultPrice: "500.00",
  },
  {
    name: "Insurance Filing (Form E/H)",
    description: "Filing of insurance certificates and endorsements with FMCSA.",
    category: "DOT Compliance",
    defaultPrice: "125.00",
  },
  {
    name: "BOC-3 Process Agent Filing",
    description: "Designation of process agents (BOC-3) filing required for interstate carriers.",
    category: "Registration",
    defaultPrice: "75.00",
  },
];

export const truckingTransactionCategories = [
  { name: "Fuel", description: "Diesel, gasoline, and other fuel purchases", parentCategory: "expense", isDefault: true },
  { name: "Maintenance", description: "Vehicle repairs, parts, and preventive maintenance", parentCategory: "expense", isDefault: true },
  { name: "Tolls", description: "Highway and bridge toll charges", parentCategory: "expense", isDefault: true },
  { name: "Insurance", description: "Vehicle, cargo, and liability insurance premiums", parentCategory: "expense", isDefault: true },
  { name: "Payroll", description: "Driver wages, benefits, and payroll taxes", parentCategory: "expense", isDefault: true },
  { name: "Permits", description: "Operating permits, oversize/overweight permits", parentCategory: "expense", isDefault: true },
  { name: "Equipment", description: "Truck parts, trailers, and equipment purchases", parentCategory: "expense", isDefault: true },
  { name: "Meals", description: "Driver meals and per diem expenses", parentCategory: "expense", isDefault: true },
  { name: "Parking", description: "Truck parking and rest stop fees", parentCategory: "expense", isDefault: true },
  { name: "License & Registration", description: "Vehicle registration, CDL renewals, and licensing fees", parentCategory: "expense", isDefault: true },
  { name: "Lease Payments", description: "Truck and trailer lease or loan payments", parentCategory: "expense", isDefault: true },
  { name: "Office", description: "Office supplies, software, and administrative costs", parentCategory: "expense", isDefault: true },
  { name: "Professional Services", description: "Accounting, legal, and consulting fees", parentCategory: "expense", isDefault: true },
  { name: "Taxes", description: "IFTA, HVUT, and other tax payments", parentCategory: "expense", isDefault: true },
  { name: "Freight Revenue", description: "Income from hauling freight and loads", parentCategory: "income", isDefault: true },
  { name: "Fuel Surcharge", description: "Fuel surcharge income from shippers", parentCategory: "income", isDefault: true },
  { name: "Accessorial Income", description: "Detention, layover, and stop-off charges", parentCategory: "income", isDefault: true },
  { name: "Other Income", description: "Miscellaneous income not categorized elsewhere", parentCategory: "income", isDefault: true },
  { name: "Other Expense", description: "Miscellaneous expenses not categorized elsewhere", parentCategory: "expense", isDefault: true },
];

export const truckingRecurringTemplates = [
  {
    name: "IFTA Quarterly Filing",
    serviceType: "IFTA Permit",
    description: "Quarterly IFTA tax return filing. Requires fuel receipts and mileage records.",
    priority: "high",
    frequencyType: "quarterly",
    daysBefore: 30,
    requiredDocuments: JSON.stringify(["Fuel Receipts", "Mileage Report"]),
  },
  {
    name: "UCR Annual Registration",
    serviceType: "UCR Registration",
    description: "Annual Unified Carrier Registration renewal.",
    priority: "medium",
    frequencyType: "annual",
    daysBefore: 60,
    requiredDocuments: JSON.stringify(["Current UCR Certificate"]),
  },
  {
    name: "MCS-150 Biennial Update",
    serviceType: "MCS-150 Update",
    description: "Biennial update of motor carrier census information.",
    priority: "medium",
    frequencyType: "biennial",
    daysBefore: 60,
    requiredDocuments: JSON.stringify(["Fleet Size Report", "Driver Count"]),
  },
  {
    name: "Annual DOT Compliance Review",
    serviceType: "DOT Permit",
    description: "Comprehensive annual DOT compliance audit and documentation review.",
    priority: "high",
    frequencyType: "annual",
    daysBefore: 45,
    requiredDocuments: JSON.stringify(["Insurance Certificate", "Vehicle Inspection Reports", "Driver Qualification Files"]),
  },
];

export const truckingCustomFieldDefinitions = [
  {
    name: "dotNumber",
    label: "DOT Number",
    fieldType: "text",
    entityType: "client",
    required: false,
    placeholder: "e.g. DOT-1234567",
    sortOrder: 1,
    industryPackSource: "trucking",
  },
  {
    name: "mcNumber",
    label: "MC Number",
    fieldType: "text",
    entityType: "client",
    required: false,
    placeholder: "e.g. MC-123456",
    sortOrder: 2,
    industryPackSource: "trucking",
  },
  {
    name: "einNumber",
    label: "EIN",
    fieldType: "text",
    entityType: "client",
    required: false,
    placeholder: "e.g. 12-3456789",
    sortOrder: 3,
    industryPackSource: "trucking",
  },
];

export const truckingSampleClients = [
  {
    companyName: "Lone Star Freight LLC",
    contactName: "Marcus Johnson",
    email: "marcus@lonestarfreight.com",
    phone: "(214) 555-0187",
    dotNumber: "DOT-3845291",
    mcNumber: "MC-982145",
    einNumber: "75-4821930",
    address: "4520 Industrial Blvd",
    city: "Dallas",
    state: "TX",
    zipCode: "75247",
    status: "active",
    notes: "Long-haul carrier, 12 trucks. Priority client.",
  },
  {
    companyName: "Summit Logistics Inc",
    contactName: "Rachel Chen",
    email: "rachel@summitlogistics.net",
    phone: "(303) 555-0294",
    dotNumber: "DOT-2917384",
    mcNumber: "MC-743829",
    einNumber: "84-3719285",
    address: "890 Mountain View Dr",
    city: "Denver",
    state: "CO",
    zipCode: "80202",
    status: "active",
    notes: "Regional carrier, specializes in refrigerated goods.",
  },
  {
    companyName: "Atlantic Coast Transport",
    contactName: "David Williams",
    email: "david@atlanticcoast.com",
    phone: "(404) 555-0341",
    dotNumber: "DOT-4829175",
    mcNumber: "MC-291847",
    einNumber: "58-9281734",
    address: "2100 Peachtree Rd NE",
    city: "Atlanta",
    state: "GA",
    zipCode: "30309",
    status: "active",
    notes: "Flatbed and dry van fleet. 8 vehicles.",
  },
  {
    companyName: "Pacific Route Carriers",
    contactName: "Lisa Park",
    email: "lisa@pacificroute.com",
    phone: "(206) 555-0412",
    dotNumber: "DOT-5738291",
    mcNumber: "MC-483921",
    einNumber: "91-8374625",
    address: "750 Harbor Ave SW",
    city: "Seattle",
    state: "WA",
    zipCode: "98126",
    status: "prospect",
    notes: "New prospect, interested in quarterly tax services.",
  },
];

export const truckingOfficialFormTemplates = [
  {
    name: "MCS-150 — Motor Carrier Identification Report",
    description: "FMCSA biennial update of motor carrier census information. Required for all carriers with a USDOT number. Due based on last digit of USDOT number.",
    category: "FMCSA Federal Forms",
    content: "FMCSA Form MCS-150 — Motor Carrier Identification Report\n\nThis form is used to update the FMCSA's motor carrier census data. All interstate motor carriers, freight forwarders, and brokers must file this form biennially.",
    fields: [
      { id: "f_usdot", label: "USDOT Number", type: "text", required: true, autoFillKey: "dot_number", width: "half", section: "Carrier Identification" },
      { id: "f_legal_name", label: "Legal Name", type: "text", required: true, autoFillKey: "company_name", width: "half", section: "Carrier Identification" },
      { id: "f_dba", label: "DBA Name (if any)", type: "text", width: "half", section: "Carrier Identification" },
      { id: "f_ein", label: "EIN (Employer ID Number)", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Carrier Identification" },
      { id: "f_address", label: "Principal Place of Business — Street", type: "text", required: true, autoFillKey: "address", width: "full", section: "Business Address" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Business Address" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Business Address" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Business Address" },
      { id: "f_phone", label: "Business Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Business Address" },
      { id: "f_email", label: "Business Email", type: "email", autoFillKey: "email", width: "half", section: "Business Address" },
      { id: "f_mailing_address", label: "Mailing Address (if different)", type: "text", width: "full", section: "Mailing Address" },
      { id: "f_mailing_city", label: "City", type: "text", width: "half", section: "Mailing Address" },
      { id: "f_mailing_state", label: "State", type: "text", width: "half", section: "Mailing Address" },
      { id: "f_mailing_zip", label: "ZIP Code", type: "text", width: "half", section: "Mailing Address" },
      { id: "f_op_class", label: "Operation Classification", type: "select", options: ["Authorized For-Hire", "Exempt For-Hire", "Private (Property)", "Private (Passengers)", "U.S. Mail", "Federal Government", "State Government", "Local Government", "Indian Tribe"], width: "half", section: "Operation Details" },
      { id: "f_carrier_op", label: "Carrier Operation", type: "select", options: ["Interstate", "Intrastate Only (Hazmat)", "Intrastate Only (Non-Hazmat)"], required: true, width: "half", section: "Operation Details" },
      { id: "f_cargo_carried", label: "Cargo Carried (select primary)", type: "select", options: ["General Freight", "Household Goods", "Metal/Sheets/Coils", "Motor Vehicles", "Drive Away/Tow Away", "Logs/Poles/Lumber", "Building Materials", "Mobile Homes", "Machinery/Large Objects", "Fresh Produce", "Liquids/Gases", "Intermodal Containers", "Passengers", "Oil Field Equipment", "Livestock", "Grain/Feed/Hay", "Coal/Coke", "Meat", "Garbage/Refuse", "US Mail", "Chemicals", "Commodities Dry Bulk", "Refrigerated Food", "Beverages", "Paper Products", "Utilities", "Agricultural/Farm Supplies", "Construction", "Water Well"], width: "half", section: "Operation Details" },
      { id: "f_hazmat", label: "Carries Hazardous Materials?", type: "select", options: ["Yes", "No"], required: true, width: "half", section: "Operation Details" },
      { id: "f_num_power_units", label: "Number of Power Units", type: "number", required: true, width: "half", section: "Equipment" },
      { id: "f_num_drivers", label: "Number of Drivers", type: "number", required: true, width: "half", section: "Equipment" },
      { id: "f_miles_driven", label: "Total Miles Driven (previous year)", type: "number", width: "half", section: "Equipment" },
      { id: "f_contact_name", label: "Authorized Official Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_title", label: "Title", type: "text", width: "half", section: "Certification" },
      { id: "f_signature_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "BOC-3 — Designation of Process Agents",
    description: "FMCSA form designating agents for service of process in each state. Required for all interstate motor carriers, brokers, and freight forwarders.",
    category: "FMCSA Federal Forms",
    content: "FMCSA Form BOC-3 — Designation of Agents for Service of Process\n\nMotor carriers, brokers, and freight forwarders must designate a process agent in each state in which they operate, plus the District of Columbia. A blanket designation through a process agent company is the most common method.",
    fields: [
      { id: "f_usdot", label: "USDOT Number", type: "text", required: true, autoFillKey: "dot_number", width: "half", section: "Carrier Information" },
      { id: "f_mc_number", label: "MC/MX/FF Number", type: "text", autoFillKey: "mc_number", width: "half", section: "Carrier Information" },
      { id: "f_legal_name", label: "Legal Name of Applicant", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Carrier Information" },
      { id: "f_address", label: "Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Carrier Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Carrier Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Carrier Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Carrier Information" },
      { id: "f_type", label: "Filing Type", type: "select", options: ["Motor Carrier of Property", "Motor Carrier of Passengers", "Broker of Property", "Broker of Passengers", "Freight Forwarder"], required: true, width: "half", section: "Carrier Information" },
      { id: "f_blanket_company", label: "Process Agent Company Name", type: "text", required: true, width: "full", section: "Process Agent Designation" },
      { id: "f_blanket_address", label: "Process Agent Address", type: "text", width: "full", section: "Process Agent Designation" },
      { id: "f_blanket_city", label: "City", type: "text", width: "half", section: "Process Agent Designation" },
      { id: "f_blanket_state", label: "State", type: "text", width: "half", section: "Process Agent Designation" },
      { id: "f_blanket_zip", label: "ZIP Code", type: "text", width: "half", section: "Process Agent Designation" },
      { id: "f_blanket_phone", label: "Phone", type: "phone", width: "half", section: "Process Agent Designation" },
      { id: "f_contact_name", label: "Authorized Signature Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_title", label: "Title", type: "text", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "UCR — Unified Carrier Registration",
    description: "Annual registration required for interstate motor carriers, brokers, freight forwarders, and leasing companies. Fee based on fleet size bracket.",
    category: "FMCSA Federal Forms",
    content: "UCR — Unified Carrier Registration Form\n\nThe Unified Carrier Registration Act requires motor carriers, brokers, freight forwarders, and leasing companies operating in interstate or international commerce to register and pay annual fees based on fleet size.",
    fields: [
      { id: "f_usdot", label: "USDOT Number", type: "text", required: true, autoFillKey: "dot_number", width: "half", section: "Carrier Identification" },
      { id: "f_legal_name", label: "Legal Name", type: "text", required: true, autoFillKey: "company_name", width: "half", section: "Carrier Identification" },
      { id: "f_mc_number", label: "MC/MX Number", type: "text", autoFillKey: "mc_number", width: "half", section: "Carrier Identification" },
      { id: "f_ein", label: "EIN", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Carrier Identification" },
      { id: "f_address", label: "Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Business Address" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Business Address" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Business Address" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Business Address" },
      { id: "f_phone", label: "Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Business Address" },
      { id: "f_email", label: "Email", type: "email", autoFillKey: "email", width: "half", section: "Business Address" },
      { id: "f_reg_year", label: "Registration Year", type: "text", required: true, width: "half", section: "Registration Details" },
      { id: "f_entity_type", label: "Entity Type", type: "select", options: ["Motor Carrier", "Motor Private Carrier", "Freight Forwarder", "Broker", "Leasing Company"], required: true, width: "half", section: "Registration Details" },
      { id: "f_fleet_size", label: "Fleet Size Bracket", type: "select", options: ["0-2 vehicles", "3-5 vehicles", "6-20 vehicles", "21-100 vehicles", "101-1,000 vehicles", "1,001+ vehicles"], required: true, width: "half", section: "Registration Details" },
      { id: "f_num_vehicles", label: "Exact Number of Vehicles", type: "number", required: true, width: "half", section: "Registration Details" },
      { id: "f_fee_amount", label: "Registration Fee", type: "text", width: "half", section: "Payment" },
      { id: "f_contact_name", label: "Authorized Official Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "IFTA — Quarterly Fuel Tax Return",
    description: "International Fuel Tax Agreement quarterly return for reporting fuel use and miles traveled in each jurisdiction. Due quarterly: Apr 30, Jul 31, Oct 31, Jan 31.",
    category: "FMCSA Federal Forms",
    content: "IFTA Quarterly Fuel Tax Return\n\nQualified motor vehicles operating in two or more IFTA member jurisdictions must file quarterly fuel tax returns. The return reports total miles driven, taxable miles in each jurisdiction, and fuel purchased.",
    fields: [
      { id: "f_ifta_license", label: "IFTA License Number", type: "text", required: true, width: "half", section: "Licensee Information" },
      { id: "f_legal_name", label: "Legal Name", type: "text", required: true, autoFillKey: "company_name", width: "half", section: "Licensee Information" },
      { id: "f_usdot", label: "USDOT Number", type: "text", autoFillKey: "dot_number", width: "half", section: "Licensee Information" },
      { id: "f_ein", label: "EIN", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Licensee Information" },
      { id: "f_address", label: "Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Licensee Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Licensee Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Licensee Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Licensee Information" },
      { id: "f_quarter", label: "Tax Quarter", type: "select", options: ["Q1 (Jan-Mar)", "Q2 (Apr-Jun)", "Q3 (Jul-Sep)", "Q4 (Oct-Dec)"], required: true, width: "half", section: "Return Period" },
      { id: "f_year", label: "Tax Year", type: "text", required: true, width: "half", section: "Return Period" },
      { id: "f_total_miles", label: "Total Miles — All Jurisdictions", type: "number", required: true, width: "half", section: "Fuel Summary" },
      { id: "f_total_gallons", label: "Total Gallons Purchased", type: "number", required: true, width: "half", section: "Fuel Summary" },
      { id: "f_avg_mpg", label: "Average MPG", type: "number", width: "half", section: "Fuel Summary" },
      { id: "f_total_taxable_gallons", label: "Total Taxable Gallons", type: "number", width: "half", section: "Fuel Summary" },
      { id: "f_net_tax_due", label: "Net Tax or Credit Due", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_penalty", label: "Penalty (if applicable)", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_interest", label: "Interest (if applicable)", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_total_due", label: "Total Amount Due", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_contact_name", label: "Preparer Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "IRS Form 2290 — Heavy Highway Vehicle Use Tax",
    description: "Annual federal excise tax return for heavy highway vehicles (55,000+ lbs GVW). Due August 31 for tax period beginning July 1.",
    category: "IRS Tax Forms",
    content: "IRS Form 2290 — Heavy Highway Vehicle Use Tax Return\n\nOwners of heavy highway motor vehicles with a taxable gross weight of 55,000 pounds or more must file Form 2290 and pay the Heavy Vehicle Use Tax (HVUT). The Stamped Schedule 1 is required as proof of payment for vehicle registration.",
    fields: [
      { id: "f_ein", label: "Employer Identification Number (EIN)", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Taxpayer Information" },
      { id: "f_legal_name", label: "Legal Name", type: "text", required: true, autoFillKey: "company_name", width: "half", section: "Taxpayer Information" },
      { id: "f_address", label: "Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Taxpayer Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Taxpayer Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Taxpayer Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Taxpayer Information" },
      { id: "f_tax_period", label: "Tax Period (beginning July 1)", type: "text", required: true, width: "half", section: "Tax Period" },
      { id: "f_final_return", label: "Final Return?", type: "select", options: ["No", "Yes"], width: "half", section: "Tax Period" },
      { id: "f_vin", label: "Vehicle Identification Number (VIN)", type: "text", required: true, width: "full", section: "Vehicle Information (Schedule 1)" },
      { id: "f_weight_category", label: "Taxable Gross Weight Category", type: "select", options: ["A: 55,000 lbs", "B: 55,001–56,000 lbs", "C: 56,001–57,000 lbs", "D: 57,001–58,000 lbs", "E: 58,001–59,000 lbs", "F: 59,001–60,000 lbs", "G: 60,001–61,000 lbs", "H: 61,001–62,000 lbs", "I: 62,001–63,000 lbs", "J: 63,001–64,000 lbs", "K: 64,001–65,000 lbs", "L: 65,001–66,000 lbs", "M: 66,001–67,000 lbs", "N: 67,001–68,000 lbs", "O: 68,001–69,000 lbs", "P: 69,001–70,000 lbs", "Q: 70,001–71,000 lbs", "R: 71,001–72,000 lbs", "S: 72,001–73,000 lbs", "T: 73,001–74,000 lbs", "U: 74,001–75,000 lbs", "V: 75,000+ lbs"], required: true, width: "half", section: "Vehicle Information (Schedule 1)" },
      { id: "f_num_vehicles_taxable", label: "Number of Taxable Vehicles", type: "number", required: true, width: "half", section: "Tax Computation" },
      { id: "f_num_vehicles_suspended", label: "Number of Suspended Vehicles (< 5,000 miles)", type: "number", width: "half", section: "Tax Computation" },
      { id: "f_total_tax", label: "Total Tax Amount", type: "text", required: true, width: "half", section: "Tax Computation" },
      { id: "f_credits", label: "Credits (if any)", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_balance_due", label: "Balance Due", type: "text", width: "half", section: "Tax Computation" },
      { id: "f_contact_name", label: "Preparer Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Signature" },
      { id: "f_title", label: "Title", type: "text", width: "half", section: "Signature" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Signature" },
      { id: "f_phone", label: "Phone", type: "phone", autoFillKey: "phone", width: "half", section: "Signature" },
    ],
  },
  {
    name: "IRP — International Registration Plan Application",
    description: "Application for apportioned registration of commercial vehicles operating in multiple jurisdictions under the International Registration Plan.",
    category: "FMCSA Federal Forms",
    content: "IRP — International Registration Plan Application\n\nThe IRP is a registration reciprocity agreement among US states, the District of Columbia, and Canadian provinces providing for payment of registration fees based on the proportion of distance operated in each jurisdiction.",
    fields: [
      { id: "f_account_number", label: "IRP Account Number", type: "text", width: "half", section: "Account Information" },
      { id: "f_usdot", label: "USDOT Number", type: "text", required: true, autoFillKey: "dot_number", width: "half", section: "Account Information" },
      { id: "f_legal_name", label: "Legal Name of Registrant", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Registrant Information" },
      { id: "f_dba", label: "DBA Name", type: "text", width: "half", section: "Registrant Information" },
      { id: "f_ein", label: "EIN/FEIN", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Registrant Information" },
      { id: "f_address", label: "Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Registrant Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Registrant Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Registrant Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Registrant Information" },
      { id: "f_phone", label: "Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Registrant Information" },
      { id: "f_base_jurisdiction", label: "Base Jurisdiction", type: "text", required: true, width: "half", section: "Registration Details" },
      { id: "f_reg_year", label: "Registration Year", type: "text", required: true, width: "half", section: "Registration Details" },
      { id: "f_fleet_type", label: "Fleet Type", type: "select", options: ["Power Unit", "Trailer", "Bus"], required: true, width: "half", section: "Registration Details" },
      { id: "f_transaction_type", label: "Transaction Type", type: "select", options: ["New Account", "Renewal", "Supplemental", "Amendment"], required: true, width: "half", section: "Registration Details" },
      { id: "f_num_vehicles", label: "Number of Vehicles in Fleet", type: "number", required: true, width: "half", section: "Vehicle Information" },
      { id: "f_vin", label: "Vehicle VIN", type: "text", width: "half", section: "Vehicle Information" },
      { id: "f_year_make_model", label: "Year / Make / Model", type: "text", width: "half", section: "Vehicle Information" },
      { id: "f_gvw", label: "Gross Vehicle Weight (GVW)", type: "number", width: "half", section: "Vehicle Information" },
      { id: "f_total_distance", label: "Total Distance (all jurisdictions)", type: "number", width: "half", section: "Distance Schedule" },
      { id: "f_contact_name", label: "Authorized Signature", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "Operating Authority Application (OP-1)",
    description: "FMCSA application for motor carrier operating authority. Required before a carrier can haul freight or passengers for hire in interstate commerce.",
    category: "FMCSA Federal Forms",
    content: "FMCSA Form OP-1 — Application for Motor Carrier Operating Authority\n\nNew motor carriers of property, passengers, household goods, or brokers must file the OP-1 form to obtain operating authority from FMCSA before commencing operations.",
    fields: [
      { id: "f_usdot", label: "USDOT Number", type: "text", autoFillKey: "dot_number", width: "half", section: "Applicant Information" },
      { id: "f_legal_name", label: "Legal Name of Applicant", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Applicant Information" },
      { id: "f_dba", label: "DBA / Trade Name", type: "text", width: "half", section: "Applicant Information" },
      { id: "f_ein", label: "EIN", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Applicant Information" },
      { id: "f_entity_type", label: "Business Entity Type", type: "select", options: ["Individual/Sole Proprietor", "Partnership", "Corporation", "LLC", "Other"], required: true, width: "half", section: "Applicant Information" },
      { id: "f_address", label: "Principal Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Business Address" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Business Address" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Business Address" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Business Address" },
      { id: "f_phone", label: "Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Business Address" },
      { id: "f_email", label: "Email", type: "email", autoFillKey: "email", width: "half", section: "Business Address" },
      { id: "f_auth_type", label: "Type of Authority Requested", type: "select", options: ["Common Carrier — Property", "Contract Carrier — Property", "Broker — Property", "Common Carrier — Passengers", "Freight Forwarder"], required: true, width: "half", section: "Authority Details" },
      { id: "f_commodities", label: "Commodities to be Transported", type: "textarea", width: "full", section: "Authority Details" },
      { id: "f_territory", label: "Territory to be Served", type: "select", options: ["48 Contiguous States", "All 50 States and DC", "Specific States (list below)"], width: "half", section: "Authority Details" },
      { id: "f_territory_specific", label: "Specific States/Territory", type: "textarea", width: "full", section: "Authority Details" },
      { id: "f_contact_name", label: "Name of Authorized Official", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_title", label: "Title", type: "text", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "BMC-91X — Surety Bond (Freight Broker/Forwarder)",
    description: "FMCSA financial responsibility filing. Freight brokers must maintain a $75,000 surety bond or trust fund agreement (BMC-84/BMC-85).",
    category: "FMCSA Federal Forms",
    content: "FMCSA Form BMC-91X — Motor Carrier Surety Bond\n\nProperty brokers and freight forwarders must file evidence of a $75,000 surety bond (BMC-84) or trust fund agreement (BMC-85) with FMCSA.",
    fields: [
      { id: "f_mc_number", label: "MC/FF Docket Number", type: "text", required: true, autoFillKey: "mc_number", width: "half", section: "Carrier/Broker Information" },
      { id: "f_usdot", label: "USDOT Number", type: "text", autoFillKey: "dot_number", width: "half", section: "Carrier/Broker Information" },
      { id: "f_legal_name", label: "Legal Name (Principal)", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Carrier/Broker Information" },
      { id: "f_address", label: "Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Carrier/Broker Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Carrier/Broker Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Carrier/Broker Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Carrier/Broker Information" },
      { id: "f_surety_company", label: "Surety Company Name", type: "text", required: true, width: "full", section: "Surety Information" },
      { id: "f_surety_address", label: "Surety Company Address", type: "text", width: "full", section: "Surety Information" },
      { id: "f_bond_number", label: "Bond Number", type: "text", required: true, width: "half", section: "Surety Information" },
      { id: "f_bond_amount", label: "Bond Amount", type: "text", required: true, placeholder: "$75,000", width: "half", section: "Surety Information" },
      { id: "f_effective_date", label: "Effective Date", type: "date", required: true, width: "half", section: "Bond Period" },
      { id: "f_expiration_date", label: "Expiration Date", type: "date", width: "half", section: "Bond Period" },
      { id: "f_contact_name", label: "Authorized Signatory", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "New Carrier Setup Packet — Intake Form",
    description: "Internal intake form for onboarding new trucking companies. Collects all information needed for DOT number, MC authority, insurance filing, and initial compliance setup.",
    category: "Business Setup",
    content: "New Carrier Setup Packet — Client Intake Form\n\nThis form collects comprehensive information needed to set up a new motor carrier including USDOT registration, operating authority application, insurance filings, and initial compliance requirements.",
    fields: [
      { id: "f_company_name", label: "Company Legal Name", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Company Information" },
      { id: "f_dba", label: "DBA / Trade Name", type: "text", width: "half", section: "Company Information" },
      { id: "f_entity_type", label: "Entity Type", type: "select", options: ["Sole Proprietorship", "LLC", "Corporation (S-Corp)", "Corporation (C-Corp)", "Partnership"], required: true, width: "half", section: "Company Information" },
      { id: "f_state_formed", label: "State of Formation", type: "text", width: "half", section: "Company Information" },
      { id: "f_ein", label: "EIN (if already obtained)", type: "text", autoFillKey: "ein_number", width: "half", section: "Company Information" },
      { id: "f_owner_name", label: "Owner / Contact Name", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Owner Information" },
      { id: "f_owner_email", label: "Email", type: "email", required: true, autoFillKey: "email", width: "half", section: "Owner Information" },
      { id: "f_owner_phone", label: "Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Owner Information" },
      { id: "f_owner_ssn_last4", label: "Owner SSN Last 4 (for 2290/IFTA)", type: "text", width: "half", section: "Owner Information" },
      { id: "f_owner_dob", label: "Owner Date of Birth", type: "date", width: "half", section: "Owner Information" },
      { id: "f_address", label: "Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Address" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Address" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Address" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Address" },
      { id: "f_num_trucks", label: "Number of Power Units (Trucks)", type: "number", required: true, width: "half", section: "Fleet Information" },
      { id: "f_num_trailers", label: "Number of Trailers", type: "number", width: "half", section: "Fleet Information" },
      { id: "f_num_drivers", label: "Number of Drivers", type: "number", width: "half", section: "Fleet Information" },
      { id: "f_cargo_type", label: "Primary Cargo Type", type: "select", options: ["General Freight", "Household Goods", "Refrigerated", "Hazmat", "Flatbed", "Tanker", "Auto Transport", "Other"], required: true, width: "half", section: "Fleet Information" },
      { id: "f_op_type", label: "Operation Type", type: "select", options: ["For-Hire (Carrier)", "Private (Own goods)", "Both"], required: true, width: "half", section: "Operations" },
      { id: "f_interstate", label: "Interstate or Intrastate?", type: "select", options: ["Interstate", "Intrastate Only", "Both"], required: true, width: "half", section: "Operations" },
      { id: "f_states_operated", label: "States Planned to Operate In", type: "textarea", width: "full", section: "Operations" },
      { id: "f_services_needed", label: "Services Requested", type: "select", options: ["Full Setup (DOT + MC + Insurance + BOC-3)", "DOT Number Only", "MC Authority Only", "Insurance Filing Only", "Compliance Package", "Other"], required: true, width: "full", section: "Services Requested" },
      { id: "f_need_ein", label: "Need EIN Application?", type: "select", options: ["Yes", "No", "Already Have One"], width: "half", section: "Services Requested" },
      { id: "f_need_boc3", label: "Need BOC-3 Filing?", type: "select", options: ["Yes", "No", "Already Filed"], width: "half", section: "Services Requested" },
      { id: "f_need_ifta", label: "Need IFTA License?", type: "select", options: ["Yes", "No", "Already Have One"], width: "half", section: "Services Requested" },
      { id: "f_need_irp", label: "Need IRP Registration?", type: "select", options: ["Yes", "No", "Already Registered"], width: "half", section: "Services Requested" },
      { id: "f_notes", label: "Additional Notes / Special Requests", type: "textarea", width: "full", section: "Notes" },
      { id: "f_date", label: "Date", type: "date", autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
  {
    name: "Driver Qualification File Checklist",
    description: "FMCSA-required driver qualification file items per 49 CFR Part 391. Use as a checklist to ensure all required documents are maintained for each driver.",
    category: "DOT Compliance",
    content: "Driver Qualification (DQ) File Checklist — 49 CFR Part 391\n\nMotor carriers must maintain a Driver Qualification file for each driver. This checklist ensures all required documents are collected and current.",
    fields: [
      { id: "f_driver_name", label: "Driver Full Name", type: "text", required: true, width: "half", section: "Driver Information" },
      { id: "f_driver_dob", label: "Date of Birth", type: "date", width: "half", section: "Driver Information" },
      { id: "f_cdl_number", label: "CDL Number", type: "text", required: true, width: "half", section: "Driver Information" },
      { id: "f_cdl_state", label: "CDL State", type: "text", width: "half", section: "Driver Information" },
      { id: "f_cdl_class", label: "CDL Class", type: "select", options: ["Class A", "Class B", "Class C"], width: "half", section: "Driver Information" },
      { id: "f_cdl_expiration", label: "CDL Expiration Date", type: "date", width: "half", section: "Driver Information" },
      { id: "f_hire_date", label: "Date of Hire", type: "date", width: "half", section: "Driver Information" },
      { id: "f_company", label: "Carrier Company", type: "text", autoFillKey: "company_name", width: "half", section: "Driver Information" },
      { id: "f_application", label: "Employment Application (391.21)", type: "checkbox", section: "Required Documents" },
      { id: "f_mvr", label: "Motor Vehicle Record (MVR) — Annual (391.25)", type: "checkbox", section: "Required Documents" },
      { id: "f_mvr_date", label: "Most Recent MVR Date", type: "date", width: "half", section: "Required Documents" },
      { id: "f_road_test", label: "Road Test Certificate or Equivalent (391.31)", type: "checkbox", section: "Required Documents" },
      { id: "f_medical_cert", label: "Medical Examiner's Certificate (391.43)", type: "checkbox", section: "Required Documents" },
      { id: "f_med_cert_exp", label: "Medical Certificate Expiration", type: "date", width: "half", section: "Required Documents" },
      { id: "f_prev_employer", label: "Previous Employer Inquiries — 3 years (391.23)", type: "checkbox", section: "Required Documents" },
      { id: "f_drug_test", label: "Pre-Employment Drug Test (382.301)", type: "checkbox", section: "Drug & Alcohol" },
      { id: "f_clearinghouse", label: "FMCSA Clearinghouse Query Completed", type: "checkbox", section: "Drug & Alcohol" },
      { id: "f_clearinghouse_date", label: "Clearinghouse Query Date", type: "date", width: "half", section: "Drug & Alcohol" },
      { id: "f_annual_review", label: "Annual Review of Driving Record (391.25)", type: "checkbox", section: "Annual Review" },
      { id: "f_annual_review_date", label: "Annual Review Date", type: "date", width: "half", section: "Annual Review" },
      { id: "f_violations", label: "Annual List of Violations (391.27)", type: "checkbox", section: "Annual Review" },
      { id: "f_notes", label: "Notes / Missing Items", type: "textarea", width: "full", section: "Notes" },
      { id: "f_reviewed_by", label: "Reviewed By", type: "text", autoFillKey: "contact_name", width: "half", section: "Review" },
      { id: "f_review_date", label: "Review Date", type: "date", autoFillKey: "today_date", width: "half", section: "Review" },
    ],
  },
  {
    name: "Vehicle Inspection Report (Annual / DVIR)",
    description: "Annual vehicle inspection report per 49 CFR 396.17 and daily Driver Vehicle Inspection Report (DVIR) per 396.11/396.13.",
    category: "DOT Compliance",
    content: "Vehicle Inspection Report\n\nCommercial motor vehicles must pass an annual inspection per 49 CFR 396.17. Drivers must also complete a DVIR at the end of each day per 396.11/396.13.",
    fields: [
      { id: "f_company", label: "Carrier Company Name", type: "text", required: true, autoFillKey: "company_name", width: "half", section: "Carrier Information" },
      { id: "f_usdot", label: "USDOT Number", type: "text", autoFillKey: "dot_number", width: "half", section: "Carrier Information" },
      { id: "f_unit_number", label: "Unit / Vehicle Number", type: "text", required: true, width: "half", section: "Vehicle Information" },
      { id: "f_vin", label: "VIN", type: "text", required: true, width: "half", section: "Vehicle Information" },
      { id: "f_year_make", label: "Year / Make / Model", type: "text", width: "half", section: "Vehicle Information" },
      { id: "f_license_plate", label: "License Plate Number", type: "text", width: "half", section: "Vehicle Information" },
      { id: "f_plate_state", label: "Plate State", type: "text", width: "half", section: "Vehicle Information" },
      { id: "f_odometer", label: "Odometer Reading", type: "number", width: "half", section: "Vehicle Information" },
      { id: "f_inspection_type", label: "Inspection Type", type: "select", options: ["Annual (396.17)", "DVIR — Pre-Trip", "DVIR — Post-Trip", "Periodic"], required: true, width: "half", section: "Inspection Details" },
      { id: "f_inspection_date", label: "Inspection Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Inspection Details" },
      { id: "f_brakes", label: "Brakes — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_lights", label: "Lights & Reflectors — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_tires", label: "Tires — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_steering", label: "Steering — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_suspension", label: "Suspension — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_exhaust", label: "Exhaust System — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_coupling", label: "Coupling Devices — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_frame", label: "Frame & Body — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_windshield", label: "Windshield / Wipers — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_horn", label: "Horn — Satisfactory?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_fire_ext", label: "Fire Extinguisher — Present?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_triangles", label: "Emergency Triangles — Present?", type: "select", options: ["Pass", "Fail", "N/A"], width: "half", section: "Inspection Items" },
      { id: "f_defects_noted", label: "Defects Noted", type: "textarea", width: "full", section: "Results" },
      { id: "f_overall_result", label: "Overall Result", type: "select", options: ["Pass — Vehicle Safe to Operate", "Fail — Vehicle Requires Repair", "Conditional — Minor Defects Noted"], required: true, width: "half", section: "Results" },
      { id: "f_inspector_name", label: "Inspector Name", type: "text", required: true, width: "half", section: "Inspector" },
      { id: "f_inspector_number", label: "Inspector ID / Certification Number", type: "text", width: "half", section: "Inspector" },
      { id: "f_inspector_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Inspector" },
    ],
  },
  {
    name: "IFTA — Annual License Application",
    description: "Application for an annual IFTA license and decals. Required for qualified motor vehicles operating in two or more IFTA jurisdictions.",
    category: "FMCSA Federal Forms",
    content: "IFTA — Annual License and Decal Application\n\nCarriers operating qualified motor vehicles in two or more IFTA member jurisdictions must obtain an IFTA license from their base jurisdiction annually.",
    fields: [
      { id: "f_legal_name", label: "Legal Name of Applicant", type: "text", required: true, autoFillKey: "company_name", width: "full", section: "Applicant Information" },
      { id: "f_dba", label: "DBA Name", type: "text", width: "half", section: "Applicant Information" },
      { id: "f_ein", label: "EIN / FEIN", type: "text", required: true, autoFillKey: "ein_number", width: "half", section: "Applicant Information" },
      { id: "f_usdot", label: "USDOT Number", type: "text", autoFillKey: "dot_number", width: "half", section: "Applicant Information" },
      { id: "f_address", label: "Business Address", type: "text", required: true, autoFillKey: "address", width: "full", section: "Applicant Information" },
      { id: "f_city", label: "City", type: "text", required: true, autoFillKey: "city", width: "half", section: "Applicant Information" },
      { id: "f_state", label: "State", type: "text", required: true, autoFillKey: "state", width: "half", section: "Applicant Information" },
      { id: "f_zip", label: "ZIP Code", type: "text", required: true, autoFillKey: "zip_code", width: "half", section: "Applicant Information" },
      { id: "f_phone", label: "Phone", type: "phone", required: true, autoFillKey: "phone", width: "half", section: "Applicant Information" },
      { id: "f_base_jurisdiction", label: "Base Jurisdiction", type: "text", required: true, width: "half", section: "License Details" },
      { id: "f_license_year", label: "License Year", type: "text", required: true, width: "half", section: "License Details" },
      { id: "f_app_type", label: "Application Type", type: "select", options: ["New License", "Renewal", "Additional Decals"], required: true, width: "half", section: "License Details" },
      { id: "f_num_vehicles", label: "Number of Qualified Motor Vehicles", type: "number", required: true, width: "half", section: "License Details" },
      { id: "f_num_decals", label: "Number of Decal Sets Requested", type: "number", required: true, width: "half", section: "License Details" },
      { id: "f_contact_name", label: "Authorized Official", type: "text", required: true, autoFillKey: "contact_name", width: "half", section: "Certification" },
      { id: "f_date", label: "Date", type: "date", required: true, autoFillKey: "today_date", width: "half", section: "Certification" },
    ],
  },
];
